# Generated by Django 3.1.3 on 2020-12-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20201214_0037'),
        ('order', '0003_auto_20201214_0037'),
        ('store', '0003_product_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
