# Generated by Django 3.1.3 on 2020-12-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20201213_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseProduct',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
